name: Avatarversalis
author: Aztl, s3nn
api-version: 1.18
version: ${project.version}
main: net.avatarverse.avatarversalis.Avatarversalis
softdepend: [PlaceholderAPI]
commands:
  bending:
    aliases: [b, avatarversalis, avatar, av, avs, pk, tla, mtla, bend]
    usage: /<command>
permissions:
  bending.admin:
    default: op